spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/autoflow
    username: autoflow_user
    password: autoflow_password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # in futuro potremo mettere validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080